CREATE TABLE test4 ( id INT NOT NULL, name VARCHAR(25) );
CREATE TABLE t2 ( d_id INT NOT NULL, name VARCHAR(25), FOREIGN KEY (d_id) REFERENCES t1(id) );
CREATE TABLE t6 ( id INT NOT NULL, name VARCHAR(25) );
CREATE TABLE t8 ( id INT NOT NULL, name VARCHAR(25), f1 FLOAT );
CREATE TABLE t1 ( id INT NOT NULL, name VARCHAR(25), f1 FLOAT, PRIMARY KEY (id) );
ALTER TABLE t3 DROP FOREIGN KEY d_id;
ALTER TABLE t3 ADD CONSTRAINT c FOREIGN KEY (d_id) REFERENCES test1(id);
ALTER TABLE t8 ADD CONSTRAINT c PRIMARY KEY (id);
ALTER TABLE t2 ADD CONSTRAINT c PRIMARY KEY (name);
ALTER TABLE t2 DROP PRIMARY KEY name;
ALTER TABLE t1 DROP PRIMARY KEY id;
ALTER TABLE test4 ADD INDEX (id);
ALTER TABLE t3 DROP INDEX (name);
INSERT INTO t6 VALUES (5, 'test8');
INSERT INTO t2 VALUES (3, 'name3');

INSERT INTO test4 VALUES (3, 'name3');
INSERT INTO test4 VALUES (2, 'name3');
INSERT INTO test4 VALUES (1, 'name3');
INSERT INTO test4 VALUES (5, 'name3');

INSERT INTO t8 VALUES (1, 't1', 0.1);
INSERT INTO t8 VALUES (2, 't2', 0.2);
INSERT INTO t8 VALUES (3, 't3', 0.3);
INSERT INTO t8 VALUES (4, 't4', 0.4);
INSERT INTO t8 VALUES (5, 't5', 0.5);

INSERT INTO t1 VALUES (1, 't1', 0.1);
INSERT INTO t1 VALUES (2, 't2', 0.2);
INSERT INTO t1 VALUES (3, 't3', 0.3);
INSERT INTO t1 VALUES (4, 't4', 0.4);
INSERT INTO t1 VALUES (5, 't5', 0.5);
INSERT INTO t1 VALUES (6, 't6', 0.5);
INSERT INTO t1 VALUES (7, 't7', 0.5);
INSERT INTO t1 VALUES (8, 't7', 0.5);

INSERT INTO t6 VALUES (10, 't7', 0.5);
INSERT INTO t6 VALUES (11, 't7', 0.5);
INSERT INTO t6 VALUES (12, 't7', 0.5);
INSERT INTO t6 VALUES (13, 't7', 0.5);
INSERT INTO t6 VALUES (14, 't7', 0.5);
INSERT INTO t6 VALUES (15, 't7', 0.5);

DELETE FROM t1 WHERE t1.id = 3;
UPDATE t2 SET name = 'saber' WHERE t1.id = 2;
SELECT * FROM t2;