CREATE TABLE test1 ( id INT NOT NULL, name VARCHAR(25), PRIMARY KEY (id) );
CREATE TABLE test2 ( d_id INT NOT NULL, name VARCHAR(25), FOREIGN KEY (d_id) REFERENCES test1(id) );
ALTER TABLE test2 DROP FOREIGN KEY d_id;
ALTER TABLE test2 ADD CONSTRAINT c FOREIGN KEY (name) REFERENCES test1(name);
ALTER TABLE test2 ADD CONSTRAINT c PRIMARY KEY (name);
ALTER TABLE test2 DROP PRIMARY KEY name;