CREATE TABLE test1 ( id INT NOT NULL, name VARCHAR(25), PRIMARY KEY (id) );
CREATE TABLE t3 ( d_id INT NOT NULL, name VARCHAR(25), FOREIGN KEY (d_id) REFERENCES test1(id) );
ALTER TABLE t3 DROP FOREIGN KEY d_id;
ALTER TABLE t3 ADD CONSTRAINT c FOREIGN KEY (d_id) REFERENCES test1(id);
ALTER TABLE t3 ADD CONSTRAINT c PRIMARY KEY (name);
ALTER TABLE t3 DROP PRIMARY KEY name;
ALTER TABLE t3 ADD INDEX (name);
ALTER TABLE t3 DROP INDEX (name);